<?php
require("global.php");
$title = "Terms of Use - Alphex";
$tab = "";

include("templates/head.php");
?>
<div class="container pb-0">
  <br>
  <h3 class="fancy">Terms of Use</h3>
  <hr>
  <p><b>Last Revised: December 19, 2016</b></p>
  <p>By accessing or using the Alphex website located at https://alphex.co (the “Site”) and any services made available through the Site (collectively, the “Services”), you (“User”) agree to be bound by these Terms of Use (“Terms”). The Services are owned and controlled by Alphex, Inc., a Delaware corporation (“Alphex”), and the terms “we,” “us,” and “our” refer to Alphex, Inc. These Terms affect your legal rights and obligations. If you do not agree to be bound by these Terms, do not access or use the Services.</p>
  <p>Alphex reserves the right to change or modify the terms and conditions contained in these Terms, including but not limited to any policy or guideline of the Site, at any time and at its sole discretion. We will provide notice of these changes by posting the revised Terms to the Site and changing the "Last Revised" date at the top of the Terms, or by emailing users at their provided email addresses, or by any other means as determined by Alphex. The decision of which notification chosen will be left to Alphex's sole discretion. Using a particular form of notice in some instances does not obligate us to use the same form in other instances. Any changes or modifications will be effective immediately upon posting the revisions to the Site or at the instant that Alphex transmits the information to the users (e.g. via email). These changes will apply at that instant to all then current and subsequent uses of the Site. You waive any right you may have to receive specific notice of such changes or modifications. Your continued use of this Site acts as acceptance of such changes or modifications. If you do not agree to the Terms in effect when you access or use the Site, you must stop using the Site.</p>
  <p><b>PREAMBLE</b></p>
  <p>Alphex provides an online tool (the “Platform”) that allows users to freely trade between a number of different virtual currencies (“Cryptocurrency”).</p>
  <p><b>1. ELIGIBILITY</b></p>
  <p>By accessing or using the Site, you represent and warrant that you are at least 18 years old and have not previously been suspended or removed from the Site. You also represent and warrant that you are not a resident of the State of New York. You represent and warrant that you are not: (a) located in, under the control of, or a national or resident of any country to which the United States has embargoed goods or services, (b) identified as a "Specially Designated National", or (c) placed on the Commerce Department's Denied Persons List. You further represent and warrant that you will not use the Site if the laws of your country prohibit you from doing so in accordance with these Terms. Finally, you represent and warrant that you will not be using this site for any illegal activity, including but not limited to money laundering and the financing of terrorism.</p>
  <p><b>2. REGISTRATION AND ACCOUNT</b></p>
  <p>In order to access and use the Services, you must create an account with Alphex (an “Account”). You agree to: (a) provide accurate, current and complete information when creating the account; (b) maintain and promptly update your Account information to keep it accurate, complete, and current; (c) maintain the security and confidentiality of your login credentials and restrict access to your Account and your computer; (d) promptly notify Alphex if you discover or otherwise suspect any security breaches related to the Site; and (e) take responsibility for all activities that occur under your Account and accept all risks of unauthorized access.</p>
  <p><b>3. PRIVACY POLICY</b></p>
  <p>Your privacy is important to us. We only share your information with third parties as outlined in our <a href="/privacy">Privacy Policy</a> or required to do so by law enforcement, court order, or in compliance with legal reporting obligations.</p>
  <p><b>4. CONFIDENTIALITY OF THE TRANSMISSION OF INFORMATION OVER THE INTERNET</b></p>
  <p>The transmission of data or information (including communications by e-mail) over the Internet or other publicly accessible networks is not one hundred percent secure, and is subject to possible loss, interception, or alteration while in transit. Accordingly, Alphex does not assume any liability, without limitation, for any damage you may experience or costs you may incur as a result of any transmissions over the Internet or other publicly accessible networks, including but not limited to transmissions involving the Platform or e-mail with Alphex containing your personal information. While Alphex will take commercially reasonable efforts to safeguard the privacy of the information you provide to Alphex and will treat such information in accordance with Alphex's Privacy Policy, in no event will the information you provide to Alphex be deemed to be confidential, create any fiduciary obligations for Alphex, or result in any liability for Alphex in the event that such information is negligently released by Alphex or accessed by third parties without Alphex's consent.</p>
  <p><b>5. Alphex DOES NOT PROVIDE INVESTING ADVICE</b></p>
  <p>We are an execution-only service and do not advise on the merits of any particular transactions or their taxation consequences. In entering into any transaction on the Platform, you represent that you have been, are, and will be solely responsible for making your own independent appraisal and investigations into the risks of the transaction. You represent that you have sufficient knowledge, market sophistication, professional advice and experience to make your own evaluation of the merits and risks of any transaction. We give you no warranty as to the suitability of the cryptocurrencies traded under these Terms and assume no fiduciary duty in our relations with you.</p>
  <p>If at any point Alphex or its representatives do provide trading recommendations, market commentary, or any other information, the act of doing so is incidental to your relationship with us and imposes no obligation of truth or due diligence on behalf of Alphex or its representatives. We give no representation, warranty, or guarantee as to the accuracy or completeness of any such information or as to the tax consequences of any transaction.</p>
  <p><b>6. MARGIN TRADING</b></p>
  <p>Margin trading on Alphex is HIGH RISK. You may sustain a total loss of funds, or owe money beyond what you have deposited to your Account. The high volatility and substantial risk of illiquidity in markets means that you may not always be able to liquidate your position.</p>
  <p>If the value of the assets in your Account falls below the maintenance margin requirement or Alphex determines, at its sole discretion, that your Account appears to be in danger of defaulting on a loan, Alphex may seize and liquidate any or all of your positions and assets on any balance in your Account in order to settle your debt to lenders. If, after your positions and assets are liquidated, your account still contains insufficient funds to settle your debts to lenders, you will be responsible for any additional funds owed. Intentionally defaulting on a loan may result in Alphex reporting your activities to authorities and/or in legal prosecution.</p>
  <p>Although Alphex takes several precautions to prevent a user from defaulting on a loan, the high volatility and substantial risk of illiquidity in markets means that Alphex cannot make any guarantees against default. When you lend to other users using the Platform’s P2P lending system, you risk the loss of an unpaid principle if the borrower defaults on a loan and liquidation of the borrower's account fails to raise sufficient funds to cover his or her debt.</p>
  <p>All trading, margin trading, lending, and/or borrowing is conducted by Users, and Alphex does not take any responsibility for any loss or damage incurred as a result of your use of any services Alphex provides or your failure to understand the risks involved in your use of such services.</p>
  <p><b>7. LIMITED LICENSE</b></p>
  <p>Alphex grants you a limited, nonexclusive, nontransferable license, subject to these Terms, to access and use the Services, and the content, materials, information and functionality available in connection therewith (collectively, the “Content”) solely for information, transactional, or other approved purposes as permitted by Alphex from time to time. Any other use of the Services or Content is expressly prohibited. All other rights in the Platform or Content are reserved by us and our licensors. You will not otherwise copy, transmit, distribute, sell, resell, license, de-compile, reverse engineer, disassemble, modify, publish, participate in the transfer or sale of, create derivative works from, perform, display, incorporate into another website, or in any other way exploit any of the Content or any other part of the Services or any derivative works thereof, in whole or in part for commercial or non-commercial purposes.  Without limiting the foregoing, you will not frame or display the Site or Content (or any portion thereof) as part of any other web site or any other work of authorship without the prior written permission of Alphex. If you violate any portion of these Terms, your permission to access and use the Platform may be terminated pursuant to these Terms.  In addition, we reserve the right to all remedies available at law and in equity for any such violation. “Alphex.co”, “Alphex”, and all logos related to the Services or displayed on the Site are either trademarks or registered marks of Alphex or its licensor.  You may not copy, imitate or use them without Alphex’s prior written consent.</p>
  <p><b>8. COPYRIGHT INFRINGEMENT</b></p>
  <p>If you believe anything on the Site infringes upon any copyright which you own or control, you may file a notification of such infringement with our Designated Agent as set forth below.</p>
  <p>
    Alphex, Inc.<br>
    1013 Centre Rd, Suite 403-B<br>
    Wilmington, DE 19801<br>
    Attn: Copyright Agent
  </p>
  <p>Please see 17 U.S.C. §512(c)(3) for the requirements of a proper notification. You should note that if you knowingly misrepresent in your notification that the material or activity is infringing, you will be liable for any damages, including costs and attorneys' fees, incurred by us or the alleged infringer as the result of our relying upon such misrepresentation in removing or disabling access to the material or activity claimed to be infringing.</p>
  <p><b>9. 51% AND OTHER CRYPTOCURRENCY ATTACKS</b></p>
  <p>Alphex makes every commercially reasonable attempt to help prevent and mitigate cryptocurrency attacks. If Alphex is able to confirm that a cryptocurrency active on the Platform has been compromised or is under attack, Alphex may immediately halt trading, deposits, and withdrawals for such cryptocurrency. If it is determined that such an attack caused the cryptocurrency to greatly decrease in value, Alphex may discontinue trade activity on such cryptocurrency entirely. Resolutions concerning deposits, withdrawals, and user balances for an attacked cryptocurrency will be determined on a case-by-case basis. Alphex makes no representation and does not warrant the safety of the Platform and is not liable for any lost value or stolen property, whether or not Alphex was negligent in providing the proper security.</p>
  <p><b>10. BSA / FinCEN</b></p>
  <p>Alphex is registered with FinCEN as an MSB (Money Services Business), registration number 31000055869849. Alphex may be required to file details of account activity to this organization from time to time.</p>
  <p><b>11. (AML) Anti-Money Laundering &amp; (KYC) Know Your Customer Policy</b></p>
  <p>Alphex protects itself from involvement in any activity that facilitates money laundering or other criminal activities by following the FinCEN guidance for MSB’s operating in the United States.</p>
  <p>Alphex aims to reasonably identify each user by cross-checking user data against governmental watch lists such as OFAC, as well as 3rd party identity verification and authentication services. If a user or a user’s transaction is flagged as suspicious through our internal controls, Alphex will require additional proof of identification from the user and has the right to not permit any trades, deposits, and/or withdrawals until additional and verifiable proof of identity is received and the Compliance Officer has approved the user for use of the Platform.</p>
  <p>By agreeing to our Terms, you acknowledge and understand that Alphex maintains verification levels which require user participation and verification in order to obtain, with leveled permissions based on user-supplied information, our ability to verify it, and our internal policies. You accept that you may not be able to achieve a desired level of verification, and Alphex reserves the right to determine, at its sole discretion, the appropriate Verification Level for any user, as well as the right to downgrade users without prior notice. Alphex may, from time to time, implement policies restricting Verification Levels by nationality, country of residence, or any other factor. This may affect your ability to withdraw funds in your account and you indemnify Alphex against any losses associated with an inability to deposit and/or withdraw funds based on your verification level.</p>
  <p><b>12. THIRD PARTY CONTENT</b></p>
  <p>Alphex and its users may provide third party content on the Site and may provide links to web pages and content that are not owned or controlled by Alphex (collectively the "Third Party Content") as a service to those interested in this information. Alphex does not control, endorse, or adopt any Third Party Content and makes no representation or warranties of any kind regarding the Third Party Content, including but not limited to its accuracy or completeness. You acknowledge and agree that Alphex is not responsible or liable in any manner for any Third Party Content and undertakes no responsibility to update or review any Third Party Content. You acknowledge that your use of such Third Party Content is at your own risk. Your business dealings or correspondence with, or participation in promotions of, any third parties, and any terms, conditions, warranties, or representations associated with such dealings or promotions, are solely between you and such third parties. Alphex is not responsible or liable for any loss or damage of any sort incurred as the result of any such dealings or promotions or as the result of the presence of such Third Party Content on the Site.</p>
  <p><b>13. COPYRIGHT OF FEEDBACK MATERIALS</b></p>
  <p>You acknowledge and agree that any materials, including but not limited to questions, comments, feedback, suggestions, ideas, plans, notes, drawings, original or creative materials or other information, regarding Alphex or the Services (collectively, "Feedback") that are provided by you, whether by email, posting to the Site or otherwise, are non-confidential and will become the sole property of Alphex. Alphex will own exclusive rights, including all intellectual property rights, and will be entitled to the unrestricted use and dissemination of such Feedback for any purpose, commercial or otherwise, without acknowledgment or compensation to you.</p>
  <p><b>14. USER CONDUCT AND OBLIGATIONS</b></p>
  <p>In connection with your use of the Services, you will not:</p>
  <ul>
    <li>Violate or assist any party in violating any law, statute, ordinance, regulation or any rule of any self-regulatory or similar organization of which you are or are required to be a member through your use of the Services;</li>
    <li>Provide false, inaccurate or misleading information;</li>
    <li>Infringe upon Alphex’s or any third party’s copyright, patent, trademark, or intellectual property rights;</li>
    <li>Distribute unsolicited or unauthorized advertising or promotional material, any junk mail, spam, or chain letters;</li>
    <li>Reverse engineer or disassemble any aspect of the Site or Services in an effort to access any source code, underlying ideas and concepts, and algorithms;</li>
    <li>Take any action that imposes an unreasonable or disproportionately large load on our infrastructure, or detrimentally interfere with, intercept, or expropriate any system, data, or information;</li>
    <li>Transmit or upload any material to the Site that contains viruses, Trojan horses, worms, or any other harmful or deleterious programs;</li>
    <li>Otherwise attempt to gain unauthorized access to the Site, other Alphex Accounts, computer systems or networks connected to the Site, through password mining or any other means; or</li>
    <li>Transfer any rights granted to you under these Terms.</li>
  </ul>
  <p><b>15. TRANSFERABILITY</b></p>
  <p>While the Account and the Services provided to a user are not transferable under any circumstance and shall be used only by the user, Alphex shall have the right to transfer, assign, or sell all the rights, benefits, or obligations to any person and these Terms shall continue to be in force and effect for the benefit of the successors and assigns of Alphex.</p>
  <p><b>16. ELECTRONIC TRADING TERMS</b></p>
  <p>A transaction on the Platform may fail for several reasons, including but not limited to change in seller prices, insufficient margin, unspecified lot size or unanticipated technical difficulties. We make no representation or warrant that any transaction will be executed properly. Alphex is under no circumstances liable for any loss or injury suffered by a failure of a transaction to complete properly. Further, Alphex is in no way responsible for notifying you of a transaction failure. The User has full responsibility to determine and inquire into the failure of any transaction the User initiates.</p>
  <p>In the event that you receive any data, information or software other than that which you are entitled to receive pursuant to these Terms, you will immediately notify us and will not use, in any way whatsoever, such data, information or software. If you request a withdrawal of funds from your Account and we cannot comply with it without closing some part of your open positions, we will not comply with the request until you have closed sufficient positions to allow you to make the withdrawal.</p>
  <p>We shall be entitled to act for you upon instructions given by or purporting to be given by you or any person authorized on your behalf without further inquiry as to the genuineness, authority, or identity of the person giving or purporting to give such instructions, provided such instruction is accompanied by correct information about your Account.</p>
  <p>Alphex reserves the right to refuse to process, or the right to cancel or reverse, any transaction on the Platform where Alphex suspects the transaction involves money laundering, terrorist financing, fraud, or any other type of crime, as legally required as an MSB, or if Alphex suspects the transaction related to Prohibited Use as stated in our Terms of Use.</p>
  <p><b>17. PERMANENT WITHDRAWAL OF SERVICE</b></p>
  <p>Alphex may (a) suspend or terminate your access to the Services, and (b) deactivate or cancel your Account as required by a valid subpoena or court order, or if Alphex reasonably suspects you of using your Account in furtherance of illegal activity. You will be permitted to transfer cryptocurrency associated with your Account for ninety (90) days after Account deactivation or cancellation unless such transfer is otherwise prohibited (i) under the law, or (ii) by a valid subpoena or court order. If any transaction is in a pending state at the time your Account is cancelled or suspended, such transaction may be cancelled and/or refunded as appropriate. You may not cancel your Account to evade an investigation or avoid paying any amounts otherwise due to Alphex. Upon cancellation of your Account, you authorize Alphex to cancel or suspend pending transactions and, after providing written notice to the you, return the funds associated with such transactions to your wallet address. In the event that you or Alphex terminates this agreement or your access to the Services, or deactivates or cancels your Account, you will remain liable for all amounts due hereunder. In the event that a technical problem causes system outage or account errors, Alphex may temporarily suspend access to your Account until the problem is resolved.</p>
  <p><b>18. OWNERSHIP OF FUNDS</b></p>
  <p>You hereby certify to us that any funds used by you in connection with the Platform are either owned by you or that you are validly authorized to carry out transactions using such funds, and that all transactions initiated with your Account are for your own account and not on behalf of any other person or entity.</p>
  <p><b>19. INDEMNIFICATION</b></p>
  <p>You agree to indemnify, defend and hold Alphex, its affiliates and service providers, and each of their respective officers, directors, agents, joint venturers, employees, and representatives, harmless from any claim or demand (including attorneys’ fees and costs and any fines, fees or penalties imposed by any regulatory authority) arising out of or related to (i) your breach of these Terms, (ii) your use of Services, or (iii) your violation of any law, rule, or regulation, or the rights of any third party.</p>
  <p><b>20. DISCLAIMER OF WARRANTEES</b></p>
  <p>Alphex PROVIDES NO GUARANTEE AS TO THE PERFORMANCE OR THE UNINTERRUPTED AVAILABILITY OF THE SERVICES. THE SERVICES ARE PROVIDED ON AN "AS IS," "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED. Alphex DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT WITH RESPECT TO THE SERVICES. Alphex DOES NOT REPRESENT OR WARRANT THAT THE SERVICES AND THE INFORMATION CONTAINED THEREIN ARE ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. Alphex WILL MAKE REASONABLE EFFORTS TO ENSURE THAT TRANSACTIONS ON THE PLATFORM ARE PROCESSED IN A TIMELY FASHION, BUT MAKES NO REPRESENTATIONS OR WARRANTIES WITH RESEPCT TO THE AMOUNT OF TIME NEEDED TO PROCESS SUCH TRANSACTIONS. BECAUSE CRYPTOCURRENCY TRANSFERS ON AND OFF THE PLATFORM ARE DEPENDENT UPON MANY FACTORS OUTSIDE OF OUR CONTROL, Alphex MAKES NO REPRESENTATIONS OR WARRANTIES REGARDING THE SUCCESS OF, OR THE AMOUNT OF TIME NEEDED FOR, CRYPTOCURRENCY TRANSACTIONS.</p>
  <p>SOME JURISDICTIONS DO NOT ALLOW THE DISCLAIMER OF IMPLIED TERMS IN CONTRACTS WITH CONSUMERS, SO SOME OR ALL OF THE DISCLAIMERS IN THIS SECTION MAY NOT APPLY TO YOU.</p>
  <p><b>21. LIMITATION OF LIABILITY</b></p>
  <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, Alphex SHALL HAVE NO LIABILITY FOR ANY DAMAGES OF ANY KIND (INCLUDING WITHOUT LIMITATION INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR TORT DAMAGES, OR LOST PROFITS) IN CONNECTION WITH YOUR USE OF THE SERVICES, EVEN IF Alphex HAS BEEN ADVISED OR IS AWARE OF THE POSSIBILITY OF SUCH DAMAGES. IN NO EVENT WILL Alphex’S LIABILITY FOR MONEY DAMAGES UNDER THESE TERMS EXCEED THE AMOUNT OF FEES RECEIVED FROM YOU DURING THE PRECEDING SIX (6) MONTH PERIOD.</p>
  <p><b>22. APPLICABLE LAW AND VENUE</b></p>
  <p>These Terms and your use of the Services will be governed by and construed in accordance with the laws of New York, without resort to its conflict of law provisions. You agree that any action at law or in equity arising out of or relating to these Terms not subject to arbitration (as set forth below), will be filed only in the state courts of Tompkins County, New York or the Federal Courts of the Northern District of New York. You hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction of such courts over any suit, action or proceeding arising out of these Terms.</p>
  <p><b>23. ARBITRATION</b></p>
  <p>Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under your use of the Services shall be finally settled on an individual basis through confidential, binding arbitration in accordance with the American Arbitration Association's rules for arbitration of consumer-related disputes and you and Alphex hereby expressly waive trial by jury. The arbitration shall take place in New York, New York, in the English language and the arbitral decision may be enforced in any court. At your request, hearings may be conducted in person or by telephone and the arbitrator may provide for submitting and determining motions on briefs, without oral hearings. The prevailing party in any action or proceeding to enforce this agreement shall be entitled to costs and attorneys' fees. Additionally, you hereby waive your right to participate in a class action lawsuit or class-wide arbitration.</p>
  <p><b>24. SURVIVAL</b></p>
  <p>Sections 11 (Third Party Content), 12 (Feedback), 18 (Indemnification), 19 (Disclaimer of Warranties), 20 (Limitation on Liability), 21 (Applicable Law and Venue), 23 (Survival), 24 (Severability), and 26 (Force Majeure) will survive any termination or expiration of these Terms.</p>
  <p><b>25. SEVERABILITY</b></p>
  <p>If any provision of these Terms is deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from these Terms and will not affect the validity and enforceability of any remaining provisions.</p>
  <p><b>26. INTEGRATION</b></p>
  <p>The failure of us to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. These Terms and any policies or operating rules posted by us constitutes the entire agreement and understanding between you and us and govern your use of the Services, superseding any prior or contemporaneous agreements, communications and proposals, whether oral or written, between you and us (including, but not limited to, any prior versions of these Terms). Any ambiguities in the interpretation of these Terms shall not be construed against the drafting party.</p>
  <p><b>27. FORCE MAJEURE</b></p>
  <p>In addition to applicable disclaimers stated above, Alphex's performance under these Terms shall be excused in the event of interruption and/or delay due to, or resulting from, causes beyond its reasonable control, including but not limited to acts of God, acts of any government, war or other hostility, civil disorder, the elements, fire, flood, earthquake, explosion, embargo, acts of terrorism, power failure, equipment failure, industrial or labor disputes or controversies, acts of any third party data provider(s) or other third party information provider(s), third party software, or communication method interruptions.</p>
  <p><b>28. GOVERNING LANGUAGE AND TRANSLATIONS</b></p>
  <p>You agree that these Terms, Alphex's Privacy Policy and other notices posted through the Services have been drafted in English. Although translations in other languages of any of the foregoing documents may be available, such translations may not be up to date or complete. Accordingly, you agree that in the event of any conflict between the English language version of the foregoing documents and any other translations thereto, the English language version of such documents shall govern.</p>
  <p><b>29. QUESTIONS AND CONTACT INFORMATION</b></p>
  <p>Please check the Twitter account before contacting support: <a href="https://twitter.com/alphexco">Alphex Twitter</a></p>
  <p>To contact support, go to <a href="http://alphex.freshdesk.com/">Alphex Support</a> and open a ticket. Please provide all relevant information, including your Alphex username and transaction IDs of any related deposits. Although we make no representations or provide no warranties about the speed of response, we will get back to you as soon as possible, typically within 24 hours.</p>
</div>
<?php
include("templates/footer.php");
?>
